/* eslint-disable @typescript-eslint/naming-convention  */
export const TermModelConstant = {
  AWARD: 'award',
  BLOB: 'blob',
  SYMBOL: 'symbol',
  CONTENT_TYPE: 'Content-Type',
  AMP_TERM_DATE: '&termDate=',
  URL_TERM_ID: '?termId=',
  URL_REPORT: '/report',
  HTML_A_ELEMENT: 'a',
  CASH_PERF: 'CSHPERF',
  RSU_PERF: 'RSUPERF',
  TABLE_HEADER: 'TableHeaders',
  CASH: 'CSH',
  USD: 'USD',
  YES: 'Yes',
  NO: 'No',
  Y: 'Y',
  N: 'N',
  XTRACID: 'xtracId',
  CLOSED: 'closed',
  RULE_ID: 'ruleId',
  DAY: 'day',
  MONTH: 'month',
  DAYS: 'days',
  MONTHS: 'months',
  AND: ' and ',
  SOP: 'SOP',
  SAR: 'SAR',
  YEAR: 'year',
  DEFAULT: 'default',
  TERMINATION_DATE: 'terminationDate',
  VESTIMMEDIATELY: 'vest immediately',
  ID: 'id',
  UPDATE: 'update',
  VIDEO: 'video',
  ESPPFLAG: '&esppIndicator=',
};

export const TermModelStoreConstants = {
  TERM_MODELS_KEY: 'termModels',
  CONTENT_KEY: 'content',
  TERM_IDS_KEY: 'termRuleIds',
  EMPLOYMENT_DETAILS_KEY: 'employmentDetails',
  TERMINATION_UPDATE_KEY: 'terminationUpdate',
};
