{
    "apiMsg": {
        "id": "000000",
        "text": "Success",
        "category": "business",
        "severity": "informational",
        "priority": null,
        "parameter": []
    },
    "entitlements": [
        "Spark.User.DocumentPreview.View",
        "Spark.User.ProratedTerminations.View",
        "Spark.User.LoadFile.View",
        "Spark.User.AddTransferAgentContact.View",
        "Spark.User.DevelopmentSupport.Update",
        "Spark.User.WebContentManagement.View",
        "Spark.User.InboundFileDetailsforClients.View",
        "Spark.User.DividendDERecords.View",
        "Spark.User.RestrictedStockApprovals.View",
        "Spark.User.AlertConfiguration.View",
        "Spark.User.Plans.View",
        "Spark.User.MessageSummary.View",
        "Spark.User.CustomSeparationRules.View",
        "Spark.User.SFTPRequestManagement.View",
        "Spark.User.DistributionSchedules.View",
        "Spark.User.InternalContactSummary.View",
        "Spark.User.GTMSTaxCodes.View",
        "Spark.User.AlertSelection.View",
        "Spark.User.CSRSchedules.View",
        "Spark.User.GrantSummary.View",
        "Spark.User.DocumentLibrary.View",
        "Spark.User.GrantUpdate.View",
        "Spark.User.TerminationAdjustment.View",
        "Spark.User.LegacyTaxDetail.View",
        "Spark.User.Access",
        "Spark.User.MBTRecentActivity.View",
        "Spark.User.ParticipantInformation.View",
        "Spark.User.DomesticTaxCodes.View",
        "Spark.User.PlanDocuments3.0.View",
        "Spark.User.GTMSTaxDetail.View",
        "Spark.User.PerformanceParameters.View",
        "Spark.User.ContactHistory.View",
        "Spark.User.LegacyTaxRates.View",
        "Spark.User.AddOtherContact.View",
        "Spark.User.ProductMapping.View",
        "Spark.User.PerformanceSchedules.View",
        "Spark.User.AlertDistribution.View",
        "Spark.User.Clients.View",
        "Spark.User.GrantLoadManagement.View",
        "Spark.User.PerformanceAdjustments.View",
        "Spark.User.AuthorizationSummary.View",
        "Spark.User.ContactLookup.View",
        "Spark.User.TerminationSchedules.View",
        "Spark.User.DividendSetup.View",
        "Spark.User.Products.View",
        "Spark.User.VestingSchedules.View",
        "Spark.User.AddAuthorizedContact.View",
        "Spark.User.MobilityTracking.View",
        "Spark.User.GrantMaintenance.View",
        "Spark.User.ClientReportingImplementation.Read",
        "Spark.User.FinancialReporting.Read",
        "Spark.User.CurrencyRate.View",
        "Spark.User.ProcessData.View",
        "Spark.User.Currency.View",
        "Spark.User.ClientControl.View",
        "Spark.User.BlackoutsBlackins.View",
        "Spark.User.Mailing.View",
        "Spark.User.CSRActivity.View",
        "Spark.User.ParticipantESPPSummary.View",
        "Spark.User.ProcessMonitor.View",
        "Spark.User.ClientOfferings.View",
        "Spark.User.AssignInternalContact.View",
        "Spark.User.AcquisitionUpdate.View",
        "Spark.User.TransferAgentSummary.View",
        "Spark.User.InternationalTaxCodes.View",
        "Spark.User.PerformancePlanDynamicNames.View",
        "Spark.User.PAMePAM.View",
        "Spark.User.PlanDocuments.View",
        "Spark.User.GrkTermSchedules.View",
        "Spark.User.GrkTermSchedules.Update",
        "Spark.User.GrkQuickReferenceGuide.View"
    ]
}
